登录成功，获取 session
请求失败，状态码: 404
Traceback (most recent call last):
  File "/home/Anorak/miniconda3/envs/work/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/Anorak/miniconda3/envs/work/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/Anorak/miniconda3/envs/work/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/Anorak/miniconda3/envs/work/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Anorak/tools/order/new_order2.py", line 5, in <module>
    book.pre_book()
  File "/home/Anorak/tools/order/book.py", line 76, in pre_book
    print(response.json()['message'])
  File "/home/Anorak/miniconda3/envs/work/lib/python3.9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
登录成功，获取 session
预约成功！
预订成功
